/**
 * Icon shim — maps former Lucide icon names to Phosphor equivalents.
 * All component code imports from '@/lib/icons'; this file is the
 * single place to update if icons need to change.
 */
export {
  Heartbeat        as Activity,
  Warning          as AlertTriangle,
  WarningCircle    as AlertCircle,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight  as ArrowRightLeft,
  ArrowCircleUp    as ArrowUpCircle,
  ArrowsDownUp     as ArrowUpDown,
  ArrowUpRight,
  Seal             as Award,
  Money            as Banknote,
  ChartBar         as BarChart3,
  Bell,
  Buildings        as Building2,
  Prohibit         as Ban,
  Robot            as Bot,
  Car,
  Calendar,
  CalendarCheck,
  CalendarDots     as CalendarDays,
  Check,
  CheckCircle      as CheckCircle2,
  CaretUpDown      as ChevronsUpDown,
  CaretDown        as ChevronDown,
  CaretLeft        as ChevronLeft,
  CaretRight       as ChevronRight,
  ClipboardText    as ClipboardList,
  Clock,
  Coins,
  Copy,
  CreditCard,
  Crown,
  Database,
  DownloadSimple   as Download,
  Drop             as Droplets,
  Eye,
  EyeSlash         as EyeOff,
  FileText,
  Funnel           as Filter,
  Gift,
  Globe,
  Hash,
  Heart,
  Info,
  SquaresFour      as LayoutDashboard,
  GridFour         as LayoutGrid,
  Rows             as LayoutList,
  FunnelSimple     as ListFilter,
  CircleNotch      as Loader2,
  Lock,
  SignOut          as LogOut,
  Envelope         as Mail,
  EnvelopeOpen     as MailCheck,
  EnvelopeSimple   as MailX,
  MapPin,
  Medal,
  Megaphone,
  List             as Menu,
  Chat             as MessageSquare,
  Moon,
  DotsThree        as MoreHorizontal,
  Package,
  Palette,
  Paperclip,
  PencilSimple     as Pencil,
  Percent,
  Phone,
  Play,
  Plus,
  Printer,
  RadioButton      as CircleDot,
  Receipt,
  ArrowClockwise   as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk       as Save,
  Article          as ScrollText,
  MagnifyingGlass  as Search,
  PaperPlaneTilt   as Send,
  GearSix          as Settings,
  Shield,
  ShieldWarning    as ShieldAlert,
  ShieldCheck,
  ShieldSlash      as ShieldOff,
  ShoppingCart,
  SlidersHorizontal,
  DeviceMobile     as Smartphone,
  Sparkle          as Sparkles,
  Square,
  Star,
  Sun,
  Tag,
  Target,
  Ticket,
  ToggleLeft,
  ToggleRight,
  Trash            as Trash2,
  TrendDown        as TrendingDown,
  TrendUp          as TrendingUp,
  Trophy,
  Truck,
  UploadSimple     as Upload,
  User,
  UserCheck,
  UserGear         as UserCog,
  UserPlus,
  Users,
  UserMinus        as UserX,
  Wallet,
  Wrench,
  X,
  XCircle,
  Lightning        as Zap,
} from '@phosphor-icons/react'
